namespace Concordium.Sdk.Types;

/// <summary>
/// An event generated by a smart contract.
/// </summary>
public sealed record ContractEvent(byte[] Bytes)
{
    /// <summary>
    /// Return hex representation.
    /// </summary>
    public string ToHex() => Convert.ToHexString(this.Bytes).ToLowerInvariant();
}
