name: Build and deploy documentation

on:
  workflow_dispatch:

jobs:
    publish-docs:
      runs-on: ubuntu-20.04
      steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: .NET Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - run: dotnet tool update -g docfx
      - run: docfx docs/docfx.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
